import { TSalesmanTableAdvertisement } from "@/types";

export const ADVERTISEMENTS: TSalesmanTableAdvertisement[] = [
    {
        id: 1,
        advertisement: {
            date: "12 мая в 10:37",
            name: "Объявление №1235",
            defaultCheckboxValue: true,
        },
        balance: 1000,
        cashback: { money: 100, percent: 20 },
        CTR: 4,
        inFavorite: 287,
        inTransactions: 36,
        product: {
            image: "/images/stub/product-stub-3.png",
            name: "Портативная зарядка для телефона",
            number: "109299492",
        },
        ransoms: [15, 25],
        ransomsQnt: 218,
        views: 387,
        defaultStatusValue: true,
    },
    {
        id: 2,
        advertisement: {
            date: "12 мая в 10:37",
            name: "Объявление №1235",
            defaultCheckboxValue: true,
        },
        balance: 1000,
        cashback: { money: 100, percent: 20 },
        CTR: 4,
        inFavorite: 287,
        inTransactions: 36,
        product: {
            image: "/images/stub/product-stub-3.png",
            name: "Портативная зарядка для телефона",
            number: "109299492",
        },
        ransoms: [15, 25],
        ransomsQnt: 218,
        views: 387,
        defaultStatusValue: true,
    },
    {
        id: 3,
        advertisement: {
            date: "12 мая в 10:37",
            name: "Объявление №1235",
            defaultCheckboxValue: true,
        },
        balance: 1000,
        cashback: { money: 100, percent: 20 },
        CTR: 4,
        inFavorite: 287,
        inTransactions: 36,
        product: {
            image: "/images/stub/product-stub-3.png",
            name: "Портативная зарядка для телефона",
            number: "109299492",
        },
        ransoms: [15, 25],
        ransomsQnt: 218,
        views: 387,
        defaultStatusValue: true,
    },
    {
        id: 4,
        advertisement: {
            date: "12 мая в 10:37",
            name: "Объявление №1235",
            defaultCheckboxValue: true,
        },
        balance: 1000,
        cashback: { money: 100, percent: 20 },
        CTR: 4,
        inFavorite: 287,
        inTransactions: 36,
        product: {
            image: "/images/stub/product-stub-3.png",
            name: "Портативная зарядка для телефона",
            number: "109299492",
        },
        ransoms: [15, 25],
        ransomsQnt: 218,
        views: 387,
        defaultStatusValue: true,
    },
];
