import { TChatPlaqueProps } from '@/types'

export const CHATS: TChatPlaqueProps[] = [
	{
		id: 1,
		avatar: '/images/stub/avatar.png',
		isOnline: true,
		lastOnlineTime: '12:35',
		productName: 'Зарядка для iphone 20W type-c быстрое устройство',
		lastMessage: undefined,
		newMessagesQnt: 0,
	},
	{
		id: 2,
		avatar: '/images/stub/avatar.png',
		isOnline: false,
		lastOnlineTime: '12:35',
		productName: 'Пеньюар парикмахерский накидка для стрижки и окрашивания',
		lastMessage: undefined,
		newMessagesQnt: 213,
	},
	{
		id: 3,
		avatar: '/images/stub/avatar.png',
		isOnline: true,
		lastOnlineTime: '12:35',
		productName: 'Электробритва беспроводная шейвер',
		lastMessage: 'Ожидание заказа  29 : 40',
		newMessagesQnt: 213,
	},
	{
		id: 4,
		avatar: '/images/stub/avatar.png',
		isOnline: true,
		lastOnlineTime: '12:35',
		productName: 'Электробритва беспроводная шейвер',
		lastMessage: 'Ожидание заказа  29 : 40',
		newMessagesQnt: 213,
	},
	{
		id: 5,
		avatar: '/images/stub/avatar.png',
		isOnline: true,
		lastOnlineTime: '12:35',
		productName: 'Электробритва беспроводная шейвер',
		lastMessage: 'Ожидание заказа  29 : 40',
		newMessagesQnt: 213,
	},
	{
		id: 6,
		avatar: '/images/stub/avatar.png',
		isOnline: true,
		lastOnlineTime: '12:35',
		productName: 'Электробритва беспроводная шейвер',
		lastMessage: 'Ожидание заказа  29 : 40',
		newMessagesQnt: 213,
	},
	{
		id: 7,
		avatar: '/images/stub/avatar.png',
		isOnline: true,
		lastOnlineTime: '12:35',
		productName: 'Электробритва беспроводная шейвер',
		lastMessage: 'Ожидание заказа  29 : 40',
		newMessagesQnt: 213,
	},
	{
		id: 8,
		avatar: '/images/stub/avatar.png',
		isOnline: true,
		lastOnlineTime: '12:35',
		productName: 'Электробритва беспроводная шейвер',
		lastMessage: 'Ожидание заказа  29 : 40',
		newMessagesQnt: 213,
	},
]
