import { TSalesmanTableProduct } from "@/types";

export const PRODUCTS: TSalesmanTableProduct[] = [
    {
        id: 1,
        advertisements: 2143,
        conversion: 32,
        product: {
            image: "/images/stub/product-stub-2.png",
            name: "Крем для тела с эффект омалаживающий",
            number: "2321321",
        },
        ransoms: [15, 25],
        ransomsQnt: 14,
        views: 2100,
        defaultCheckboxValue: true,
        defaultStatusValue: true,
    },
    {
        id: 2,
        advertisements: 2143,
        conversion: 32,
        product: {
            image: "/images/stub/product-stub-2.png",
            name: "Крем для тела с эффект омалаживающий",
            number: "2321321",
        },
        ransoms: [15, 25],
        ransomsQnt: 14,
        views: 2100,
        defaultCheckboxValue: false,
        defaultStatusValue: true,
    },
    {
        id: 3,
        advertisements: 2143,
        conversion: 32,
        product: {
            image: "/images/stub/product-stub-2.png",
            name: "Крем для тела с эффект омалаживающий",
            number: "2321321",
        },
        ransoms: [15, 25],
        ransomsQnt: 14,
        views: 2100,
        defaultCheckboxValue: false,
        defaultStatusValue: false,
    },
    {
        id: 4,
        advertisements: 2143,
        conversion: 32,
        product: {
            image: "/images/stub/product-stub-2.png",
            name: "Крем для тела с эффект омалаживающий",
            number: "2321321",
        },
        ransoms: [15, 25],
        ransomsQnt: 14,
        views: 2100,
        defaultCheckboxValue: false,
        defaultStatusValue: true,
    },
    {
        id: 5,
        advertisements: 2143,
        conversion: 32,
        product: {
            image: "/images/stub/product-stub-2.png",
            name: "Крем для тела с эффект омалаживающий",
            number: "2321321",
        },
        ransoms: [15, 25],
        ransomsQnt: 14,
        views: 2100,
        defaultCheckboxValue: false,
        defaultStatusValue: false,
    },
    {
        id: 6,
        advertisements: 2143,
        conversion: 32,
        product: {
            image: "/images/stub/product-stub-2.png",
            name: "Крем для тела с эффект омалаживающий",
            number: "2321321",
        },
        ransoms: [15, 25],
        ransomsQnt: 14,
        views: 2100,
        defaultCheckboxValue: true,
        defaultStatusValue: false,
    },
];
